### ISSUE TITLE
تایید بازگشت کتاب

### ISSUE THREAD

**Issue by Pirasteh77** [Qolzam/qc-test#4]
در برنامه کتابدار:
با وجود تایید بازگشت امانت کتابهای تحویلی ب مربی و ثبت تعداد نسخه های برگشتی و تعداد کاربرگ ها ولی هیچ تغییری در بخش دیرکردها ایجاد نمیشه و کتاب هایی ک دیرکرد داشتن همچنان باقی هستن(رفرش و همگام سازی هم انجام شد)

**Comment by Qolzam** [comment]
تشکر از توضیح 🙏🏼
امکان داره من منظور شما رو به خوبی متوجه نشده باشم. اگر منظور شما تایید بازگشت کتاب های دیرکرد و حذف آنها از لیست امانت ها هست، این مشکل باید حل شده باشه. لطفا بررسی کنید اگر مشکل حل نشده یا منظور شما به درستی فهم نشده دوباره با جزییات بررسی کنیم.

**Comment by Pirasteh77** [comment]
تو برنامه کتابدار،امانت کتاب ها حذف میشن ولی تو برنامه مربی کتاب ها همچنان هستن و تغییری نمیکنه منظور من اینه

**Comment by Qolzam** [comment]
امکان داره اسکرین شات از امانت قبل از ثبت و  از صفحه مربی برای قبل و بعد از تایید بازگشت کتابدار بفرستید؟🙏🏼 
@Pirasteh77

**Comment by Pirasteh77** [comment]
[
![Screenshot_20230212-173911_library-gtr](https://user-images.githubusercontent.com/125119335/218316133-601872e7-fc66-4436-8058-6392a0934754.jpg)
](url)

این صفحه مربی هستش


![Screenshot_20230212-173855_library-gtr](https://user-images.githubusercontent.com/125119335/218316163-b7f18cd7-c876-4b00-8e24-538c7bf00928.jpg)

این صفحه کتابدار هستش

**Comment by Qolzam** [comment]
تشکر برای اسکرین شات🙏🏼
میشه در قسمت مربی روی کتاب "قندیل کوچک" بزنید و چیزی در قسمت موجودی هست بفرستید؟
@Pirasteh77
