### ISSUE TITLE
وجود باگ در کادر تعداد نسخه های امانت

### ISSUE THREAD

**Issue by Pirasteh77** [Qolzam/qc-test#6]
برنامه کتابدار:
در بخش امانت کتاب با کلیک بر روی کادر تعداد نسخه برای وارد کردن تعداد کتاب های امانت داده شده ب مربی پس از چندین ثانیه توقف کادر موجود ابی شده و حرکتی نمیکند و باید از کل برنامه خارج شد و دوباره وارد شد تا بتوان تعداد رو وارد کرد

**Comment by Qolzam** [comment]
تشکر برای وقت و توضیح 🙏🏼
متاسفانه نتونستم این مشکل رو پیدا کنم. امکانش هست یک screen record داشته باشید و مشخصات اندروید رو بفرستید؟


![image](https://user-images.githubusercontent.com/8446573/218265526-c1760e6e-7f3f-4893-9602-b006720fcf45.png)

**Comment by Pirasteh77** [comment]
مشکل موردنظر حل شد.وقتی موجودی کتاب یک عدد باشه امکان تغییر یا کلیک روی کادر نیست ب همین خاطر من فک کردم باگ هستش
