### ISSUE TITLE
تایید بازگشت از طرف مربی

### ISSUE THREAD

**Issue by Pirasteh77** [Qolzam/qc-test#8]
در برنامه مربی:
وقتی کتابدار کتابی را تایید بازگشت یا انصراف از امانت میزنه در برنامه مربی با وجود همگام سازی اطلاعات داده و همچنین رفرش صفحه همچنان کتاب ها وجود داره و حذف نشدند

**Comment by Qolzam** [comment]
تشکر برای تست و توضیح 🙏🏼
زمانی که مربی کتاب رو به امانت میگره موجودی کتاب به تعداد کپی امانت هست


<img width="491" alt="image" src="https://user-images.githubusercontent.com/8446573/218262480-4eb5da33-531c-4a13-9c64-43a21c70e04e.png">


ولی زمانی که کتابدار کپی ها رو برگشت میزنه موجودی صفر میشه که امکان امانت اون کتاب دیگه وجود نداره برای مربی. علتش این هست که داده به صورف آفلاین وجود داره و اگر مربی به تاریخچه امانت یک دانش آموز نیاز داشته باشه می تونه اون کتاب ها رو ببینه. البته نیازی نیست که در لیست کتاب ها قرار داشته یا می تونه باشه به عنوان تاریخچه کتاب هایی که مربی امانت گرفته برای خود مربی.
ممنون میشم نظرتون رو بدونم.
<img width="491" alt="image" src="https://user-images.githubusercontent.com/8446573/218263069-1787074e-bdfc-4b3d-962b-6a888eddc958.png">

**Comment by Pirasteh77** [comment]
با سلام.مشکل اینه که کتابدار کتاب موردنظر رو تایید برگشت میزنه و قاعدتا در برنامه مربی باید موجودی اون کتاب صفر بشه و امکان امانت اون کتاب وجود نداشته باشه.ولی این جوری نیست و برای مثال الان در برنامه کتابدار 1 کتاب به امانت مربی تست هست ولی در برنامه مربی تست با وجود همگام سازی و رفرش مجدد همچنان 4 کتاب وجود داره برای امانت...

**Comment by Qolzam** [comment]
ممنون از توضیحات . دوباره بررسی میشه🙏🏼
